all: ui-mpu-6050-with-oled-on-arduino-uno ui-mpu-6050-with-oled-on-nrf52840

.PHONY: clean ui-mpu-6050-with-oled-on-arduino-uno ui-mpu-6050-with-oled-on-nrf52840

ui-mpu-6050-with-oled-on-arduino:
	$(MAKE) -C ui-mpu-6050-with-oled-on-arduino-uno

ui-mpu-6050-with-oled-on-nrf52840:
	$(MAKE) -C ui-mpu-6050-with-oled-on-nrf52840

clean:
	$(MAKE) -C ui-mpu-6050-with-oled-on-arduino clean
